### ISSUE TITLE
update babel-eslint

### ISSUE THREAD

**Issue by michalica** [ableneo/modules#23]
<img width="562" alt="Snímka obrazovky 2019-08-22 o 12 54 19" src="https://user-images.githubusercontent.com/16046334/63509247-fb080700-c4db-11e9-8abf-c3f7454f51e1.png">

Newest react-script requires babel-eslint@10.0.2

**Comment by marcelmokos** [comment]
Do you suggest adding it as dependeci? Currently, there is not in the dependency it means we need to update package that is using it to a newer version.

**Comment by marcelmokos** [comment]
Updated in #24

**Comment by marcelmokos** [comment]
Resolved/Updated in #24
